dbdata:
  image: ubuntu
  volumes:
    - /var/lib/mysql
db:
  image: mysql
  volumes_from:
    - dbdata
  environment:
    - MYSQL_DATABASE=mytestdb
  env_file:
    - .env
app:
  extends:
    file: common.yml
    service: app 
  volumes: 
    - .:/usr/src/app
  restart: no
  links:
    - db:mysql
 
